In [9]:
import pandas as pd
import matplotlib.pyplot as plt

import csv

In [26]:
llm_results_filename = './data/results/partial_results.csv'
df_llm_results = pd.read_csv(llm_results_filename)

manual_results_filename = "./data/results/manual_results.csv"
df_manual_results = pd.read_csv(manual_results_filename)

In [28]:
df_manual_results.rename(columns={"Unnamed: 0": "pmcid",
                                  "Contains human subjects or samples?": "human_presence",
                                  "Does the study report individual participants or biological samples from individual organisms, excluding cell lines and tissue samples from the same organism?": "multi_samples",
                                  "Contains sex and/or sample quantitative data?": "participant_demographics",
                                  "Are there multiple cohorts, disaggregated data or individual-level data?": "multi_cohorts",
                                  "Sex-specific phenotype": "sex_specific_phenotype"}, inplace=True)

In [25]:
#df_manual_results = df_manual_results[selected_columns]
df_manual_results

,human_presence,participant_demographics,sex_specific_phenotype,multi_samples,multi_cohorts
0,True,True,False,True,True
1,True,True,False,True,True
2,True,True,False,True,True
3,True,True,True,True,False
4,True,True,False,True,False
...,...,...,...,...,...
95,True,True,False,True,True
96,True,False,False,False,False
97,True,True,True,True,True
98,True,True,False,True,True
99,False,False,False,False,False

In [16]:
# Define the correct column order
desired_order = ["human_presence", "participant_demographics", "sex_specific_phenotype", "multi_samples", "multi_cohorts"]

# Reorder the columns
df_manual_results = df_manual_results[desired_order]
df_llm_results = df_llm_results[desired_order]
df_manual_results

,human_presence,participant_demographics,sex_specific_phenotype,multi_samples,multi_cohorts
0,True,True,False,True,True
1,True,True,False,True,True
2,True,True,False,True,True
3,True,True,True,True,False
4,True,True,False,True,False
...,...,...,...,...,...
95,True,True,False,True,True
96,True,False,False,False,False
97,True,True,True,True,True
98,True,True,False,True,True
99,False,False,False,False,False

In [18]:
df_llm_results

,human_presence,participant_demographics,sex_specific_phenotype,multi_samples,multi_cohorts
0,True,False,False,False,False
1,True,True,True,True,False
2,True,False,True,False,False
3,True,True,True,True,False
4,True,True,False,True,False
...,...,...,...,...,...
94,True,True,True,True,True
95,False,False,False,False,False
96,True,True,True,True,True
97,True,True,False,True,True
98,True,False,False,False,False

In [8]:
import pandas as pd

# Define the columns to compare
selected_columns = [
    "human_presence", 
    "participant_demographics", 
    "sex_specific_phenotype", 
    "multi_samples", 
    "multi_cohorts"
]

# Ensure both DataFrames are aligned
df_manual_results = df_manual_results.sort_index().reset_index(drop=True)
df_llm_results = df_llm_results.sort_index().reset_index(drop=True)

# Perform comparison on selected columns only
df_comparison = df_manual_results[selected_columns] == df_llm_results[selected_columns]

# Convert to Boolean values if needed (ensures proper True/False format)
df_comparison = df_comparison.astype(bool)

# Optionally, add an identifier column if the original DataFrames had more information
df_comparison.insert(0, "index", df_manual_results.index)

# Display the result
print(df_comparison)

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

In [21]:
# Define the columns to compare
selected_columns = [
    "human_presence", 
    "participant_demographics", 
    "sex_specific_phenotype", 
    "multi_samples", 
    "multi_cohorts"
]

# Select only relevant columns and ensure column order is the same
df_manual_selected = df_manual_results[selected_columns].copy()
df_llm_selected = df_llm_results[selected_columns].copy()

# Ensure both DataFrames have the same index (reset if needed)
df_manual_selected = df_manual_selected.reset_index(drop=True)
df_llm_selected = df_llm_selected.reset_index(drop=True)

# Now perform the comparison
df_comparison = df_manual_selected == df_llm_selected

# Convert to Boolean values explicitly (optional)
df_comparison = df_comparison.astype(bool)

# Optionally, add an identifier if needed
df_comparison.insert(0, "index", df_manual_results.index)

# Display the result
print(df_comparison)

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects